name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        with:
          platforms: linux/amd64,linux/arm64
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: topcarryu/efb-bot-action
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
          platforms: linux/amd64,linux/arm64
